language: python
python:
- '2.7'
before_install:
- cd GradePredictorApp/codes
install:
- pip install -r ../../requirements.txt
- python setup.py install
- cd ..
- export APP_CONFIG='production'
script:
- nosetests tests/BackEndTests.py
- nosetests tests/FrontEndTests.py
deploy:
  provider: heroku
  api_key:
    secure: VgtiUu7aWITNzng6FYjUsJ8aHultCPan9xHDHDm3mo76tF2Deo5yYOHMaLMIdVuMVGbpLVT16zuNbbF0F7o7pE6VaLEXa0tj5oEWkUhrhKy25K2uquo7fHlDom8NS8OQWLWQRmlTxso+9+S8EKhE4KLL2+3+6leiRJShIV14i3yZt91LOT7n/4VaqWsKKuAZlki4MSJBAQXXmu4pceA9NHKmQk6+KTAdndlLPZAmmSR8AVDloBcdUc2xr5SuA13+9wIuwrJwreYxG2mM16LIC33W+GiGLZCBjFxRxbpdPmL7Kf9HeucWr04tf3sJnvUb243z7v4/k0236sFH3s4b/LNOvf3lBuLeUvF+i/QKjINQTxPmSW6tofmH5BXQ2+dfuUaoV0ye1WGai4WwEecyA6FAqX88UuJke1mFpNkfG1gu3g431k0MEhUGfXvnMxtlyjc0Fc2c1aowtHl2PDnqdFnjeuA1em+Vn5dwMTyI0QPdHFBfwfTJEok4Gnb3fcviFX2t9lSsruC0KSpaf8n1dyEwCriPASbL0vDfkCzsJvbnL6JGoIlDqtmWO2T7q/EFYG1TMUEC9Qga+IF5CyNB3DaWNk0DCRXlhZfLW0t6PtRUUmTF8Qx86DM2JgCg20xEw01zFLpdupsCNXcNuntU1h46YYulKizEWjdLojsLNHA=
  app: grade-predictor-app
  on:
    all_branches: true
    tags: true
